### ISSUE TITLE
mandatory dependency on QuickCheck

### ISSUE THREAD

**Issue by giogadi** [3of8/heap#1]
First off, thanks for your work on this library! It's been a big help for my work.

When building this from Hackage, the library automatically pulls in QuickCheck as a dependency, even though QuickCheck isn't actually part of the package's interface. I think this can be fixed by changing the test target from an "Executable" to a "Test-Suite" ([example](https://github.com/giogadi/kdt/blob/master/kdt.cabal)).

**Comment by pruvisto** [comment]
Thanks for the suggestion. I didn't actually do a lot of work on it, I
just took over the package from the previous maintainer because there
were some issues that I needed to have fixed and he wasn't maintaining
it actively anymore.

I'll consider what you suggested and implement it as soon as I find the
time.

**Comment by pruvisto** [comment]
Oops, I'm terribly sorry, I completely forgot about this. I tried to do what you suggested and uploaded the new version to Hackage.
